# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1089, 729)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.photos = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photos.sizePolicy().hasHeightForWidth())
        self.photos.setSizePolicy(sizePolicy)
        self.photos.setMinimumSize(QtCore.QSize(0, 0))
        self.photos.setTabShape(QtGui.QTabWidget.Rounded)
        self.photos.setDocumentMode(False)
        self.photos.setTabsClosable(True)
        self.photos.setMovable(True)
        self.photos.setObjectName(_fromUtf8("photos"))
        self.view_1 = QtGui.QWidget()
        self.view_1.setObjectName(_fromUtf8("view_1"))
        self.photos.addTab(self.view_1, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.photos, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPlik = QtGui.QMenu(self.menubar)
        self.menuPlik.setObjectName(_fromUtf8("menuPlik"))
        self.menuEdycja = QtGui.QMenu(self.menubar)
        self.menuEdycja.setObjectName(_fromUtf8("menuEdycja"))
        self.menuOkno = QtGui.QMenu(self.menubar)
        self.menuOkno.setObjectName(_fromUtf8("menuOkno"))
        self.menuZdj_cia = QtGui.QMenu(self.menubar)
        self.menuZdj_cia.setObjectName(_fromUtf8("menuZdj_cia"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget_4 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_4.setMinimumSize(QtCore.QSize(298, 192))
        self.dockWidget_4.setAutoFillBackground(False)
        self.dockWidget_4.setStyleSheet(_fromUtf8(""))
        self.dockWidget_4.setFloating(False)
        self.dockWidget_4.setObjectName(_fromUtf8("dockWidget_4"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.directories = QtGui.QTreeWidget(self.tab)
        self.directories.setFrameShape(QtGui.QFrame.NoFrame)
        self.directories.setFrameShadow(QtGui.QFrame.Plain)
        self.directories.setObjectName(_fromUtf8("directories"))
        self.gridLayout_3.addWidget(self.directories, 0, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.tab)
        self.splitter_2.setMinimumSize(QtCore.QSize(70, 32))
        self.splitter_2.setMaximumSize(QtCore.QSize(69, 32))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.pushButton_3 = QtGui.QPushButton(self.splitter_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_3.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.splitter_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_4.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout = QtGui.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Albums = QtGui.QListWidget(self.tab_2)
        self.Albums.setFrameShape(QtGui.QFrame.NoFrame)
        self.Albums.setFrameShadow(QtGui.QFrame.Plain)
        self.Albums.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.Albums.setObjectName(_fromUtf8("Albums"))
        self.gridLayout.addWidget(self.Albums, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.tab_2)
        self.splitter.setMinimumSize(QtCore.QSize(70, 32))
        self.splitter.setMaximumSize(QtCore.QSize(69, 32))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.pushButton = QtGui.QPushButton(self.splitter)
        self.pushButton.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.splitter)
        self.pushButton_2.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(32, 32))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.splitter, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.dockWidget_4.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget_4)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_2.sizePolicy().hasHeightForWidth())
        self.dockWidget_2.setSizePolicy(sizePolicy)
        self.dockWidget_2.setMinimumSize(QtCore.QSize(87, 109))
        self.dockWidget_2.setAccessibleName(_fromUtf8(""))
        self.dockWidget_2.setFloating(False)
        self.dockWidget_2.setObjectName(_fromUtf8("dockWidget_2"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.info = QtGui.QTextBrowser(self.dockWidgetContents_2)
        self.info.setMaximumSize(QtCore.QSize(3423423, 16777215))
        self.info.setAutoFillBackground(False)
        self.info.setFrameShape(QtGui.QFrame.NoFrame)
        self.info.setFrameShadow(QtGui.QFrame.Plain)
        self.info.setLineWidth(1)
        self.info.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.info.setObjectName(_fromUtf8("info"))
        self.gridLayout_4.addWidget(self.info, 0, 0, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget_2)
        self.actionInfo = QtGui.QAction(MainWindow)
        self.actionInfo.setCheckable(True)
        self.actionInfo.setChecked(True)
        self.actionInfo.setObjectName(_fromUtf8("actionInfo"))
        self.actionWidok = QtGui.QAction(MainWindow)
        self.actionWidok.setObjectName(_fromUtf8("actionWidok"))
        self.actionNawigacja = QtGui.QAction(MainWindow)
        self.actionNawigacja.setCheckable(True)
        self.actionNawigacja.setChecked(True)
        self.actionNawigacja.setObjectName(_fromUtf8("actionNawigacja"))
        self.actionObr = QtGui.QAction(MainWindow)
        self.actionObr.setObjectName(_fromUtf8("actionObr"))
        self.actionKadruj = QtGui.QAction(MainWindow)
        self.actionKadruj.setObjectName(_fromUtf8("actionKadruj"))
        self.actionPrzytnij = QtGui.QAction(MainWindow)
        self.actionPrzytnij.setObjectName(_fromUtf8("actionPrzytnij"))
        self.actionDodaj_atrybut = QtGui.QAction(MainWindow)
        self.actionDodaj_atrybut.setObjectName(_fromUtf8("actionDodaj_atrybut"))
        self.actionZmie_atrybut = QtGui.QAction(MainWindow)
        self.actionZmie_atrybut.setObjectName(_fromUtf8("actionZmie_atrybut"))
        self.actionUsu_atrybut = QtGui.QAction(MainWindow)
        self.actionUsu_atrybut.setObjectName(_fromUtf8("actionUsu_atrybut"))
        self.actionEksportuj = QtGui.QAction(MainWindow)
        self.actionEksportuj.setObjectName(_fromUtf8("actionEksportuj"))
        self.actionOtw_rz_sesj = QtGui.QAction(MainWindow)
        self.actionOtw_rz_sesj.setObjectName(_fromUtf8("actionOtw_rz_sesj"))
        self.actionWi_kszy_ni = QtGui.QAction(MainWindow)
        self.actionWi_kszy_ni.setObjectName(_fromUtf8("actionWi_kszy_ni"))
        self.actionMniejszy_ni = QtGui.QAction(MainWindow)
        self.actionMniejszy_ni.setObjectName(_fromUtf8("actionMniejszy_ni"))
        self.actionDok_adnie = QtGui.QAction(MainWindow)
        self.actionDok_adnie.setObjectName(_fromUtf8("actionDok_adnie"))
        self.actionFiltruj = QtGui.QAction(MainWindow)
        self.actionFiltruj.setObjectName(_fromUtf8("actionFiltruj"))
        self.actionSortuj = QtGui.QAction(MainWindow)
        self.actionSortuj.setObjectName(_fromUtf8("actionSortuj"))
        self.actionLimit = QtGui.QAction(MainWindow)
        self.actionLimit.setObjectName(_fromUtf8("actionLimit"))
        self.menuPlik.addAction(self.actionEksportuj)
        self.menuPlik.addAction(self.actionOtw_rz_sesj)
        self.menuEdycja.addAction(self.actionObr)
        self.menuEdycja.addAction(self.actionKadruj)
        self.menuEdycja.addAction(self.actionPrzytnij)
        self.menuEdycja.addSeparator()
        self.menuEdycja.addAction(self.actionDodaj_atrybut)
        self.menuEdycja.addAction(self.actionZmie_atrybut)
        self.menuEdycja.addAction(self.actionUsu_atrybut)
        self.menuOkno.addAction(self.actionInfo)
        self.menuOkno.addAction(self.actionNawigacja)
        self.menuZdj_cia.addAction(self.actionFiltruj)
        self.menuZdj_cia.addAction(self.actionSortuj)
        self.menuZdj_cia.addAction(self.actionLimit)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuEdycja.menuAction())
        self.menubar.addAction(self.menuOkno.menuAction())
        self.menubar.addAction(self.menuZdj_cia.menuAction())

        self.retranslateUi(MainWindow)
        self.photos.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Easypic", None))
        self.photos.setTabText(self.photos.indexOf(self.view_1), _translate("MainWindow", "widok", None))
        self.menuPlik.setTitle(_translate("MainWindow", "Plik", None))
        self.menuEdycja.setTitle(_translate("MainWindow", "Edycja", None))
        self.menuOkno.setTitle(_translate("MainWindow", "Okno", None))
        self.menuZdj_cia.setTitle(_translate("MainWindow", "Zdjęcia", None))
        self.dockWidget_4.setWindowTitle(_translate("MainWindow", "nawigacja", None))
        self.pushButton_3.setText(_translate("MainWindow", "Add", None))
        self.pushButton_4.setText(_translate("MainWindow", "Rmv", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Katalogi", None))
        self.pushButton.setText(_translate("MainWindow", "Add", None))
        self.pushButton_2.setText(_translate("MainWindow", "Rmv", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Albumy", None))
        self.dockWidget_2.setWindowTitle(_translate("MainWindow", "info", None))
        self.actionInfo.setText(_translate("MainWindow", "Info", None))
        self.actionWidok.setText(_translate("MainWindow", "widok", None))
        self.actionNawigacja.setText(_translate("MainWindow", "Nawigacja", None))
        self.actionObr.setText(_translate("MainWindow", "Obróć", None))
        self.actionKadruj.setText(_translate("MainWindow", "Kadruj", None))
        self.actionPrzytnij.setText(_translate("MainWindow", "Przytnij", None))
        self.actionDodaj_atrybut.setText(_translate("MainWindow", "Ddodaj atrybut", None))
        self.actionZmie_atrybut.setText(_translate("MainWindow", "Zmień atrybut", None))
        self.actionUsu_atrybut.setText(_translate("MainWindow", "Usuń atrybut", None))
        self.actionEksportuj.setText(_translate("MainWindow", "Zapisz sesję", None))
        self.actionOtw_rz_sesj.setText(_translate("MainWindow", "Otwórz sesję", None))
        self.actionWi_kszy_ni.setText(_translate("MainWindow", "Większy niż", None))
        self.actionMniejszy_ni.setText(_translate("MainWindow", "Mniejszy niż", None))
        self.actionDok_adnie.setText(_translate("MainWindow", "Dokładnie", None))
        self.actionFiltruj.setText(_translate("MainWindow", "Filtruj", None))
        self.actionSortuj.setText(_translate("MainWindow", "Sortuj", None))
        self.actionLimit.setText(_translate("MainWindow", "Limit", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

